version: "3.6"
services:

  python3:
    restart: unless-stopped
    build: .
    container_name: "s3s"
    working_dir: "/root/s3s"
    tty: true
    volumes:
      - ./:/root/s3s
    command: "python s3s.py -M 120 -r"
